### ISSUE TITLE
Data Persistence Bug - Screen is not updated when data is loaded from file

### ISSUE THREAD

**Issue by KnurpsBram** [KnurpsBram/shoplist#4]
Whenever you change anything in the `appData` object, it is saved to json. Whenever you initialize a widget, the `appData` object is loaded up from jsonfile. This is to make sure the app won't forget the lists the user has made (data persistence). However, after it has loaded the screen shows the default values for appData that it would have if there were no data stored on the device. As soon as you perform some action (tap a checkbox for instance), the widgets redrawn and it shows that the data was in fact loaded correctly.

Can widgets be forcibly redrawn upon loading the `appData` object from file? 
Should the load-from-file-call happen at some other place in the code?

![data_persistence_bug_28feb2021](https://user-images.githubusercontent.com/32075749/109415784-0a162200-79bb-11eb-8af9-f8a56a4be2a8.gif)

**Comment by akashrajkn** [comment]
You should override the initState method and load the appData there. Calling setState after loading appData will trigger the rebuild

**Comment by KnurpsBram** [comment]
I write

```
class _ShopListState extends State<ShopList> {

    @override
    void initState() {
        super.initState();
        appData._loadAppDataFromDisk();
        setState((){});
    }

    @override
    Widget build(BuildContext context) {

...
```

but no luck :(

**Comment by akashrajkn** [comment]
Make `_loadAppDataFromDisk` an async function (read/write to files is async). use `setState` in the .then of _loadAppDataFromDisk
